'use client';

import { useEffect, useState } from 'react';
import api from '@/utils/api';
import NewsletterCard from '@/components/NewsletterCard';
import { Loader2 } from 'lucide-react';

interface Newsletter {
    id: number;
    title: string;
    summary: string;
    content: string;
    sentiment: string;
    published_at: string;
}

export default function NewslettersPage() {
    const [newsletters, setNewsletters] = useState<Newsletter[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchNewsletters = async () => {
            try {
                const response = await api.get('/newsletters/');
                setNewsletters(response.data);
            } catch (error) {
                console.error('Failed to fetch newsletters', error);
            } finally {
                setLoading(false);
            }
        };
        fetchNewsletters();
    }, []);

    if (loading) {
        return (
            <div className="flex justify-center items-center min-h-[50vh]">
                <Loader2 className="animate-spin h-8 w-8 text-gray-400" />
            </div>
        );
    }

    return (
        <div className="max-w-6xl mx-auto px-6 py-16">
            <div className="space-y-4 mb-12">
                <div className="flex items-center gap-2">
                    <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span>
                    <span className="text-xs text-gray-400 font-semibold uppercase tracking-wider">
                        Archive Feed ({newsletters.length} Editions)
                    </span>
                </div>
                <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight bg-gradient-to-r from-white via-indigo-200 to-accent bg-clip-text text-transparent">
                    Latest Newsletter Editions
                </h1>
                <p className="text-gray-400 text-base max-w-xl">
                    Browse previous analytical summaries generated by our agent pipeline, covering sentiment indices and social trends.
                </p>
            </div>

            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                {newsletters.map((newsletter) => (
                    <NewsletterCard
                        key={newsletter.id}
                        id={newsletter.id}
                        title={newsletter.title}
                        summary={newsletter.summary}
                        sentiment={newsletter.sentiment}
                        published_at={newsletter.published_at}
                    />
                ))}
            </div>
            {newsletters.length === 0 && (
                <div className="glass-card rounded-2xl p-12 text-center max-w-md mx-auto mt-12">
                    <p className="text-gray-400 font-medium">No newsletters published yet.</p>
                </div>
            )}
        </div>

    );
}
